config/routes.rb
Rails.application.routes.draw do
  get 'books/new' 
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  get '/' => 'homes#top'
  root to: 'home#index'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :books, only: [:create, :new, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
   if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
   else
      @books = Book.all
      render :index
   end
  end

  def index
    @books = Book.all
    if params[:id].present?
      set_book
    else @book = Book.new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id]) 
    @book.destroy
    redirect_to '/books'  
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<h2><strong>Editing Book</strong></h2>

<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
   <%= @book.errors.count %>件のerrorが発生しました<ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
   <% end %>
 <% end %>
 </ul>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <h5>本のタイトル</h5>
  <%= f.text_field :title %>
  
  <h5>感想</h5>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Update Book' %>
  <br>
  <%= link_to "Show", @book %> | 
  <a href="/books">Back</a>
  
  
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
 <table>
  <thead> 
   <tr>
    <th>本のタイトル</th> 
    <th>感想</th>
    <th colspan="3"></th>
   </tr>
  </thead>
 
  <tbody>
   <% @books.each do |book| %>
   <tr>
   <td><%= book.title %></td>
   <td><%= book.body %></td>
   <td><%= link_to "Show", book_path(book.id) %></td>
   <td><%= link_to "Edit", edit_book_path(book.id) %> </td>
   <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
   </tr>
   <% end %>
  </tbody>
 </table>

<h2>New book</h2> 
 
 <%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
   <%= @book.errors.count %>件のerrorが発生しました<ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
   <% end %>
 <% end %>
 </ul>
 


<%= form_with model: @books, url: '/books', method: :post do |f| %>

<p>本のタイトル</p>
	<%= f.text_field :title %>

<p>感想</p>
	<%= f.text_area :body %>

<br><%= f.submit 'Create Book' %></br>


<% end %>

app/views/books/new.html.erb
<h3>New book</h3>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Body</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>
 
<br>
<strong>本のタイトル:</strong><%= @book.title %></p>

<br>

<strong>感想:</strong><%= @book.body %></p>

<br>

<%= link_to "Edit", edit_book_path(@book) %> | 
<a href="/books">Back</a>

app/views/homes/top.html.erb
<!DOCTYPE html>

<head>
    <title>webcamp backendnew</title>
</head>


<body>
    
<h1>ようこそ <strong>Bookers</strong> へ！</h1>

<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<a href="/books">start</a>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>